# Generated by Django 4.2.13 on 2025-03-09 02:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import portifolio.files
import portifolio.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FatoSobre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Ativo")),
                ("deleted", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "icone",
                    models.CharField(
                        blank=True,
                        help_text="Nome do ícone Lucide (https://lucide.dev)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("subtitulo", models.CharField(max_length=255)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fatos_sobre",
                        to="usuario.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fato Sobre",
                "verbose_name_plural": "Fato Sobre",
            },
        ),
        migrations.CreateModel(
            name="Foto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Ativo")),
                ("deleted", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=255)),
                (
                    "arquivo",
                    models.ImageField(
                        blank=True,
                        help_text="Arquivo da foto",
                        null=True,
                        upload_to=portifolio.files.generate_unique_file_name,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "svg"]
                            ),
                            portifolio.validators.FileSizeValidator(max_size=5),
                        ],
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="usuario.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto",
                "verbose_name_plural": "Fotos",
            },
        ),
        migrations.CreateModel(
            name="SecaoSobre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Ativo")),
                ("deleted", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "titulo",
                    models.CharField(help_text="Ex.: Sobre Mim", max_length=255),
                ),
                (
                    "descricao",
                    models.TextField(help_text="Texto da Seção Sobre", max_length=1000),
                ),
                (
                    "fatos_sobre",
                    models.ManyToManyField(
                        help_text="Crie os Fatos Sobre e eles aparecerão aqui pra serem selecionados",
                        related_name="secoes_sobre_many",
                        to="portifolio.fatosobre",
                    ),
                ),
                (
                    "imagem",
                    models.ForeignKey(
                        blank=True,
                        help_text="Imagem da seção",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="secao_sobre",
                        to="portifolio.foto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secoes_sobre",
                        to="usuario.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seção Sobre",
                "verbose_name_plural": "Seções Sobre",
            },
        ),
        migrations.CreateModel(
            name="SecaoContato",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Ativo")),
                ("deleted", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("titulo", models.CharField(max_length=255)),
                (
                    "descricao",
                    models.TextField(
                        help_text="Texto da Seção Contato", max_length=1000
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secoes_contato",
                        to="usuario.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seção Contato",
                "verbose_name_plural": "Seções Contato",
            },
        ),
        migrations.CreateModel(
            name="Parceiros",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Ativo")),
                ("deleted", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=255)),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parceiros",
                        to="portifolio.foto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parceiros",
                        to="usuario.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parceiro",
                "verbose_name_plural": "Parceiros",
            },
        ),
        migrations.CreateModel(
            name="MensagemContato",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Ativo")),
                ("deleted", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("assunto", models.CharField(max_length=255)),
                ("mensagem", models.TextField()),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagens",
                        to="usuario.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem de Contato",
                "verbose_name_plural": "Mensagens de Contato",
            },
        ),
        migrations.CreateModel(
            name="ImagemHeader",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Ativo")),
                ("deleted", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "imagem",
                    models.ForeignKey(
                        help_text="Você deve criar uma foto então poderá selecioná-la aqui, para ficar em destaque",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="header",
                        to="portifolio.foto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="headers",
                        to="usuario.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagens em Destaque",
                "verbose_name_plural": "Imagens em Destaque",
            },
        ),
        migrations.CreateModel(
            name="DadosPrincipais",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Ativo")),
                ("deleted", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(help_text="Seu nome", max_length=255)),
                (
                    "subtitulo",
                    models.TextField(
                        help_text="Texto embaixo do seu nome", max_length=1000
                    ),
                ),
                (
                    "titulo_portifolio",
                    models.CharField(
                        blank=True,
                        help_text="Ficará acima dos álbums",
                        max_length=255,
                        null=True,
                        verbose_name="Título do Portifólio",
                    ),
                ),
                (
                    "descricao_portifolio",
                    models.TextField(
                        blank=True,
                        help_text="Texto embaixo do título do portifólio",
                        max_length=1000,
                        null=True,
                        verbose_name="Descrição do Portifólio",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dados_principais",
                        to="usuario.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dados Principais",
                "verbose_name_plural": "Dados Dados Principais",
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Ativo")),
                ("deleted", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=255)),
                (
                    "icone",
                    models.CharField(
                        blank=True,
                        help_text="Nome do ícone Lucide (https://lucide.dev)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorias",
                        to="usuario.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Ativo")),
                ("deleted", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("titulo", models.CharField(max_length=255)),
                ("url", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "capa",
                    models.ForeignKey(
                        blank=True,
                        help_text="A foto que será a capa do álbum",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cover",
                        to="portifolio.foto",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        help_text="Crie as Categorias e elas aparecerão aqui pra serem selecionadas",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="albums",
                        to="portifolio.categoria",
                    ),
                ),
                (
                    "fotos",
                    models.ManyToManyField(
                        help_text="Crie as Fotos e elas aparecerão aqui pra serem selecionadas",
                        related_name="album",
                        to="portifolio.foto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albums",
                        to="usuario.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Álbum",
                "verbose_name_plural": "Álbuns",
            },
        ),
    ]
