# Generated by Django 4.2.13 on 2025-02-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="fotos",
            field=models.ManyToManyField(related_name="album", to="portifolio.foto"),
        ),
    ]
