# Generated by Django 4.2.13 on 2025-03-08 14:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0001_initial"),
        ("portifolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecaoContato",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Ativo")),
                ("deleted", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("titulo", models.CharField(max_length=255)),
                (
                    "descricao",
                    models.TextField(
                        help_text="Texto da Seção Contato", max_length=1000
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secoes_contato",
                        to="usuario.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seção Contato",
                "verbose_name_plural": "Seções Contato",
            },
        ),
        migrations.CreateModel(
            name="DadosPrincipais",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Ativo")),
                ("deleted", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(help_text="Seu nome", max_length=255)),
                (
                    "subtitulo",
                    models.TextField(
                        help_text="Texto embaixo do seu nome", max_length=1000
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dados_principais",
                        to="usuario.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dados Principais",
                "verbose_name_plural": "Dados Dados Principais",
            },
        ),
    ]
