# Generated by Django 4.2.13 on 2025-02-21 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "portifolio",
            "0002_remove_foto_url_album_capa_album_url_foto_arquivo_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foto",
            name="album",
        ),
    ]
