# Generated by Django 4.2.13 on 2025-03-08 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0002_secaocontato_dadosprincipais"),
    ]

    operations = [
        migrations.AddField(
            model_name='fatosobre',
            name='usuario',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='fatos_sobre',
                to='usuario.usuario',  # adjust the app/model name if needed
                default=1
            ),
            preserve_default=False,
        ),
    ]
