# Generated by Django 4.2.13 on 2025-02-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0003_categoria_album_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="icone",
            field=models.CharField(
                blank=True,
                help_text="Nome do ícone Lucide (https://lucide.dev)",
                max_length=100,
                null=True,
            ),
        ),
    ]
