# Generated by Django 4.2.13 on 2025-03-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0003_add_usuario_to_fatosobre"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagemheader",
            options={
                "verbose_name": "Imagens em Destaque",
                "verbose_name_plural": "Imagens em Destaque",
            },
        ),
        migrations.AddField(
            model_name="dadosprincipais",
            name="descricao_portifolio",
            field=models.TextField(
                blank=True, help_text="Texto do Portifólio", max_length=1000, null=True
            ),
        ),
        migrations.AddField(
            model_name="dadosprincipais",
            name="titulo_portifolio",
            field=models.CharField(
                blank=True, help_text="Título do Portifólio", max_length=255, null=True
            ),
        ),
    ]
