# Generated by Django 4.2.13 on 2025-03-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0004_alter_imagemheader_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dadosprincipais",
            name="descricao_portifolio",
            field=models.TextField(
                blank=True,
                help_text="Texto embaixo do título do portifólio",
                max_length=1000,
                null=True,
                verbose_name="Descrição do Portifólio",
            ),
        ),
        migrations.AlterField(
            model_name="dadosprincipais",
            name="titulo_portifolio",
            field=models.CharField(
                blank=True,
                help_text="Ficará acima dos álbums",
                max_length=255,
                null=True,
                verbose_name="Título do Portifólio",
            ),
        ),
    ]
