# Generated by Django 4.2.13 on 2025-02-25 19:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0001_initial"),
        ("portifolio", "0004_categoria_icone"),
    ]

    operations = [
        migrations.CreateModel(
            name="FatoSobre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Ativo")),
                ("deleted", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "icone",
                    models.CharField(
                        blank=True,
                        help_text="Nome do ícone Lucide (https://lucide.dev)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("subtitulo", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
            ],
            options={
                "verbose_name": "Seção Sobre",
                "verbose_name_plural": "Seções Sobre",
            },
        ),
        migrations.CreateModel(
            name="SecaoSobre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Ativo")),
                ("deleted", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                (
                    "fatos_sobre",
                    models.ManyToManyField(
                        related_name="secoes_sobre_many", to="portifolio.fatosobre"
                    ),
                ),
                (
                    "imagem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="secao_sobre",
                        to="portifolio.foto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secoes_sobre",
                        to="usuario.usuario",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Parceiros",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Ativo")),
                ("deleted", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=255)),
                ("url", models.URLField()),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parceiros",
                        to="portifolio.foto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parceiros",
                        to="usuario.usuario",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MensagemContato",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Ativo")),
                ("deleted", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("assunto", models.CharField(max_length=255)),
                ("mensagem", models.TextField()),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagens",
                        to="usuario.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem de Contato",
                "verbose_name_plural": "Mensagens de Contato",
            },
        ),
        migrations.AddField(
            model_name="fatosobre",
            name="secao_sobre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fatos_sobre_fk",
                to="portifolio.secaosobre",
            ),
        ),
    ]
