# Generated by Django 4.2.13 on 2025-02-25 19:56

import django.core.validators
from django.db import migrations, models
import portifolio.files
import portifolio.validators


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0005_fatosobre_secaosobre_parceiros_mensagemcontato_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fatosobre",
            options={"verbose_name": "Fato Sobre", "verbose_name_plural": "Fato Sobre"},
        ),
        migrations.AlterModelOptions(
            name="parceiros",
            options={"verbose_name": "Parceiro", "verbose_name_plural": "Parceiros"},
        ),
        migrations.AlterModelOptions(
            name="secaosobre",
            options={
                "verbose_name": "Seção Sobre",
                "verbose_name_plural": "Seções Sobre",
            },
        ),
        migrations.RemoveField(
            model_name="fatosobre",
            name="secao_sobre",
        ),
        migrations.AlterField(
            model_name="foto",
            name="arquivo",
            field=models.ImageField(
                blank=True,
                help_text="Arquivo da foto",
                null=True,
                upload_to=portifolio.files.generate_unique_file_name,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "svg"]
                    ),
                    portifolio.validators.FileSizeValidator(max_size=5),
                ],
                verbose_name="Arquivo",
            ),
        ),
    ]
