# Generated by Django 4.2.13 on 2025-02-25 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0006_alter_fatosobre_options_alter_parceiros_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fatosobre",
            name="descricao",
        ),
    ]
