# Generated by Django 4.2.13 on 2025-02-25 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portifolio", "0007_remove_fatosobre_descricao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="capa",
            field=models.ForeignKey(
                blank=True,
                help_text="Você deve criar uma foto então poderá selecioná-la aqui, para ser a capa do álbum",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cover",
                to="portifolio.foto",
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                help_text="Crie as Categorias e elas aparecerão aqui pra serem selecionadas",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="albums",
                to="portifolio.categoria",
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="fotos",
            field=models.ManyToManyField(
                help_text="Crie as Fotos e elas aparecerão aqui pra serem selecionadas",
                related_name="album",
                to="portifolio.foto",
            ),
        ),
        migrations.AlterField(
            model_name="imagemheader",
            name="imagem",
            field=models.ForeignKey(
                help_text="Você deve criar uma foto então poderá selecioná-la aqui, para ficar em destaque",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="header",
                to="portifolio.foto",
            ),
        ),
        migrations.AlterField(
            model_name="parceiros",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="secaosobre",
            name="descricao",
            field=models.TextField(help_text="Texto da Seção Sobre", max_length=1000),
        ),
        migrations.AlterField(
            model_name="secaosobre",
            name="fatos_sobre",
            field=models.ManyToManyField(
                help_text="Crie os Fatos Sobre e eles aparecerão aqui pra serem selecionados",
                related_name="secoes_sobre_many",
                to="portifolio.fatosobre",
            ),
        ),
        migrations.AlterField(
            model_name="secaosobre",
            name="imagem",
            field=models.ForeignKey(
                blank=True,
                help_text="Imagem da seção",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="secao_sobre",
                to="portifolio.foto",
            ),
        ),
    ]
