name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Run Tests
        run: npm run test

  docker:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t portfolio_frontend -f Dockerfile .

      - name: Run Docker Container (Validation)
        run: docker run --rm portfolio_frontend npm run test || echo "Container tests skipped"
