name: CI/CD Pipeline

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Executar Testes
        run: |
          python manage.py test
          
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Disparar Deploy
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://ricardoh.pythonanywhere.com/webhook/deploy/'
          method: 'POST'
          customHeaders: '{"X-Secret-Token": "${{ secrets.DEPLOY_TOKEN }}"}'
