name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build da imagem Docker
        run: docker build -t gerenciador_de_site_de_fotografia:latest .

      - name: Subir containers com docker-compose
        run: docker-compose -f docker-compose.yml up -d

      - name: Executar migrações
        run: docker exec web_gerenciador_de_site_de_fotografia python manage.py migrate

      - name: Executar testes com pytest
        run: docker exec web_gerenciador_de_site_de_fotografia pytest

      - name: Parar e remover containers
        run: docker-compose -f docker-compose.yml down
